// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdcovaTtC4LwaGyQlZSxl46y2saCSFXFg',
    appId: '1:629625181772:web:e317f51eda5a1d0b0c86e9',
    messagingSenderId: '629625181772',
    projectId: 't-shirt-wo',
    authDomain: 't-shirt-wo.firebaseapp.com',
    storageBucket: 't-shirt-wo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8IrIAoFjq9yUTSPet4OtGYU4k1S0QfyQ',
    appId: '1:629625181772:android:49fed50818fb90a20c86e9',
    messagingSenderId: '629625181772',
    projectId: 't-shirt-wo',
    storageBucket: 't-shirt-wo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVICTDQ8-vmMQslXhPi6J2H1yXzSOccgc',
    appId: '1:629625181772:ios:47b0a8ebdffe24700c86e9',
    messagingSenderId: '629625181772',
    projectId: 't-shirt-wo',
    storageBucket: 't-shirt-wo.appspot.com',
    iosBundleId: 'com.example.tShirtWorld',
  );
}
